spring:
  application:
    name: TaskManagement

  datasource:
    url: jdbc:mysql://localhost:3306/taskmanagement
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

jwt:
  secretKey: kL2qTg45kV+3x9S7XyB4C8s09CwhYasf8Hg5gK0qYUY=
  expirationTime: 3600000